Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-

- index.html
Fix Display Issue with "Emergency" Button on Mobile Screens
--------------------------------------------------------------------
--------------------------------------------------------------------
This pull request addresses error #4   which involved a display issue with the "Emergency" button on mobile screens. The button was becoming too small and the text was disappearing when the screen size decreased.
To fix this issue, I adjusted the styling of the "Emergency" button to ensure it remains visible and maintains a consistent size across different screen sizes. Specifically, I increased the minimum width of the button and adjusted the font size to improve readability.
> Fix Display Issue with "Emergency" Button on Mobile Screens

- Html-Files/Css-Files/appointStyle.css
- Html-Files/appointScript.js
- Html-Files/appointment.html
- Html-Files/doc.html
This is with respect to issue #170 which I was assigned.I have created an Appointment Page for for website which is triggered by "make an appointment button" on doctors page. @varshith257 @Anishkagupta04  I would request you to increase the level to level3 as it took a lot time and also I have added a JavaScript file for making it more dynamic.
> appointment page

- index.html
The header of the Rapidoc text was not in right position, which it was moved to out of the screen. Now the text is changed to right position. The header is not properly has layout and ordered.
- Closes #301 
- [X ] Bug fix
- [ X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [ X] I have performed a self-review of my code
- [ X] I have provided relevant issue numbers, screenshots, and videos after …
> Rapidoc header text is moved to right position

- index.html
Removed the 'd-none' class from the 'EMERGENCY' span within the header section to ensure the text is visible. The 'd-none' class was replaced with the 'd-md-inline' class to maintain responsive behavior, displaying the text on medium and larger screens while hiding it on smaller screens.
- Closes #328 
-Complies with accessibility best practices by making all features available to users with disabilities who might rely on responsive design features or use assistive technologies.
-Mobile and tablet users constitute a significant portion of web traffic. By making the Emergence button visible in responsive mode, the application becomes more accessible to this demographic, potentially increasing user engagement and retention.
> Updated header markup to remove 'd-none' class from 'EMERGENCY' span

- index.html
issue #103
Added Reveal Elements on scroll fasture
- Closes #
- [] Bug fix
- [] Documentation update
- [] Other (specify): _______________
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/d10556cb-cff4-4748-9183-6a5b69b588d2
Added Code:
```
<script src="https://unpkg.com/scrollreveal"></script>
<script>
ScrollReveal({ 
//reset: true ,
distance : '60px' ,
duration:2500,
delay:400
});
ScrollReveal().reveal('.d-flex,#home', { delay: 500 , origin:'top' });
ScrollReveal().reveal('.logo , .navbar,.content', { delay: 500 , …
```
> 💡[FEATURE]: 🌟 Reveal Elements On Scroll 🌟

- index.html
#382
Contact us spelling was corrected in the footer section
> corrected spelling in footer section

- index.html
Added Preloader and Custom Cursor.
-Closes #387
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/ea45b253-0abd-4a51-a257-660a9e98a6b3
Added Code:
```
<script>
//Custom Cursor
const coords = { x: 0, y: 0 };
const circles = document.querySelectorAll(".circle");
const colors = [
"#55a5ea",
"#55a5ea",
"#55a5ea",
"#55a5ea",
"#55a5ea",
"#55a5ea",
"#55a5ea",
"#55a5ea",
"#3fbcc0c6",
"#3fbcc0c6",
"#3fbcc0c6",
"#3fbcc0c6",
"#3fbcc0c6",
"#3fbcc0c6",
"fff",
"fff",
"fff",
"fff",
"fff",
"fff",
"fff"
];
circles.forEach(function (circle, …
```
> ✨[Feature Request]: Addition of Preloader and Custom Cursor.

- index.html
- style.css
Changed service containers that is more interactive and responsive now.
> Added new Service Container

- index.html
I have updated the information on services card.
- Closes #433 
- [ ✓] Documentation update
- [ x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x ] I have updated my branch and synced it with project `main` branch before making this PR
- [x ] I have performed a self-review of my code
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
> updated the info on service cards

- style.css
Hi @Anishkagupta04 ,
closes #537 
considering the current positioning where the chatbot is in the rightmost bottom of the page and the scroll-to-top button is just above it, I adjusted the scroll-to-top button to be moved to the left side of the page to avoid overlap.
******Video/Screenshots (mandatory)******
Here as you can see :
Please take a look and also add required labels.
> Resolved overlapping issue between chatbot and scroll to top button

- index.html
- style.css
Added functionality to the submit button. When the submit button is clicked, it displays the messaged, "thank you for submitting your feedback" and refreshes. If the form is not filled and the submit button is clicked,it displays"Pease fill the feedback form "message
-## Closes #703 
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142666229/b4c3852f-b001-45d5-bc13-162679feb9da
> Made the submit button functional

- Html-Files/customer_agreement.html
- Html-Files/terms_and_conditions.html
- index.html
Hey @Anishkagupta04 and @varshith257 ,
issue closes #685 
**Below are the Changes I Implemented -** 
-  I **Created two separate HTML pages** for "Customer Agreement" and "Terms and Conditions" and linked them into the footer links
- I tried my very best **to style the two pages** similar to the **website's color theme** so that visually it will look good to see.
- I **also added favicons** to both the pages as you can see in the video below.
- Additionally, I have included a footer at the end of both the pages to re-navigate to the "Home" page instead of changing the tabs manually.
Please take look to the video below - 
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/131389695/8ce2ba31-c5d9-4e23-b8e8-67394a5d1123
@varshith257 Please review the changes and let me know …
> Added "Customer Agreement" and "Terms and Conditions" Pages

- style.css
In the footer, links now have a smooth underline animation effect that expands from left to right on hover, with the text color changing to black. The underline is hidden by default and only appears during the hover state for a clean, modern look.
- Closes #699 
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/95361125/08380a1b-2925-4249-8aac-083e1173f902
> updated hover effect of footer

- index.html
- style.css
fixex 636
fix message box , text in contact us add hovering effect in cards of about us and emergency add proper link to doctors available and user review
- Closes #636 
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/159682348/c938c622-c682-4e19-84b8-0149b465a11f
closed #638 and opened this
> fix message box , text in contact us add hovering effect in cards of about us and emergency add proper link to doctors available and user review

- index.html
Fixed
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142989448/1bed9969-3355-4338-ba5d-1991797a8d0c
- Closes #794 
> updated home page css

- Css-Files/aboutus.css
Fixed overflowing of text from the cards in about us section .
Now the text is within cards and properly aligned on the about us section .
- Closes #836
> Fixed overflowing of text from the cards in about us section .

- index.css
- index.html
Changed the styling of Heading and paragraph tags to make them visible.
Earlier the heading were not visible because the background color and the text color were same.
So I changed the color of heading and paragraph.
- Closes #850 
https://github.com/user-attachments/assets/8e02cbaa-5437-4899-9ea5-cc9e5be23c77
https://github.com/user-attachments/assets/5fe40ed1-a360-455f-af2f-a738439aa679
> Changed the heading and paragraph color to make it visible

- .vscode/settings.json
- Css-Files/news.css
- news.html
#873
- Closes #873 
Vercel Deployment screenrecording
https://github.com/user-attachments/assets/6109b161-8806-4a58-9ccf-aa299b24f8d4
> 🐞[Bug]: Fixing News.html

- index.html
I have removed the br tags which were not important in the index.html file
- Closes #849 
BEFORE : 
AFTER : 
> Remove unnecessary br tags

- appointment.html
Adjusted the size of the emergency button from 16px to 30px for highlighting it.
- Closes #40 
> Adjust emergency button size for better visibility

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/auto-label-issues.yml
- .github/workflows/auto-label-pr.yml
#991
- Closes #991 
"Settings" > "Actions" > "General" and under "Workflow permissions", select "Read and write permissions".
Make sure to do the above after PR merging.
Changes template of PR.
> Auto Label Added

- dex.html
Google map integration and enhancement of contact us section under Services Tab. Also, aligned the whole section.
- Closes #787 
> Google map integration and enhancement of contact us section under Services Tab

- .github/workflows/auto-label-issues.yml
- .github/workflows/auto-label-pr.yml
- Css-Files/caduceus.css
- Css-Files/popupfeedbacksctioncss.css
- assets/css/visitors.css
- index.html
- js/popupfeedback.js
- style.css
Added an popup feedback ( made the feedback section to popup when placed cursor pointer on rate us in navbar).
- Closes #1079 
https://github.com/user-attachments/assets/68a4d374-1fa3-404a-9e99-aa47aead38ef
> ✨[Feature Request]: popup feedback

- Css-Files/Rateus.css
- Css-Files/popupfeedbacksctioncss.css
- index.html
Modified the rate us page , now the content is not flowing out of the box .
- Closes #1097
> Modified rate us page .

- Html-Files/privacy_policy_page.html
- Html-Files/terms_and_conditions.html
Hey @Anishkagupta04 and @varshith257 ,
issue closes #1137 
I have implemented a dynamic "Last Updated" date feature for the legal pages on the website, including the Terms and Conditions, Privacy Policy pages.
The date format is set to "month day, year" and will update dynamically to reflect the current date.
Additionally, each page has a specific update frequency to ensure the date remains accurate.
****Changes Made :****
Added a code to dynamically update the "Last Updated" date for the Terms and Conditions, Privacy Policy pages.
The date format is "month day, year" for a professional appearance.
Please take a look and review it.
> ✔️Added Dynamic "Last Updated" Functionality to All Legal Pages ! 

- checkup.css
- index.css
- index.html
- style.css
Fixed the navbars for various screen sizes
- Closes #1106
fixed for 768px
for 820px
for 880px
> fixed navbar

- dex.html
- index.html
- portal.html
added the patient portal page and linked it to the footer
- Closes #
> added the separate patient portal page

- .github/workflows/auto-label-pr.yml
- Css-Files/helpline.css
- Html-Files/Doctor Experience.html
- Html-Files/appointment.html
- Html-Files/blood.html
- Html-Files/bloodtest.html
- Html-Files/cardio.html
- Html-Files/news.html
- dex.html
- faq.html
- helpline.html
- index.html
- js/helpline.js
- medicine.html
- portal.html
- test.html
#1160
Helpline Page.
- Closes #1160 
https://github.com/user-attachments/assets/d8e9b60e-8b57-48e9-977d-7c2e297e9f55
@varshith257 please review the PR.
> ✨[Feature Request]: Added page

- Html-Files/appointment.html
- Html-Files/blood.html
- Html-Files/ent.html
- Html-Files/privacy_policy_page.html
- Html-Files/terms_and_conditions.html
- index.html
- medicine.html
- test.html
i have removed the testimonial and security from the footer as they were not being used from most of the pages i might have missed for some but main pages i have covered
I mentioned about this in the issue of my old pull request
- Closes #
> Removal testimonial and security from the footer

- Css-Files/helpline.css
- helpline.html
- js/helpline.js
> ✨[Feature Request]: Added of popup
