Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-

index.html
Fixed #69 
1. Integrated the Patient Portal section with the login form and forgot password link.
2. Need to create the backend logic (e.g., PHP scripts for authentication) and implement additional functionality (e.g., displaying medical records, and lab results) on subsequent pages linked from the patient portal.
Screenshots:
=> Secure Patient Portal Development

index.html, style.css
Fixed the previous PR issue, code structure same as original.
Feedback system under issue #22
=> Added feedback system

index.html
Added suitable icons for different sections in the navbar.
=> Added Icons : issue number :# 76

index.html
I have updated the old twitter logo to the new one, for this I have used fontawesome icons libraries. 
Also, I have updated the other social icons with fontawesome icon library.
Closes #67.
=> New twitter icon

index.html, successful_appointment.html
Solves issue #20 
Successful appointment will redirect to this message page with a button to navigate to the home page for better user experience.
The user will no longer be ambiguous about the success of the booking of the appointment
=> Successful-Appointment

README.md
=> Added Slack logo and link

index.html
Fixes #116 
Made the Emergency button responsive
=> Fixes: Button not responsive #116

index.html
=> Updated display of Doctor's image

index.html
issue fix #92  (Under GSSoC'24)
=> Redirect to dialer pad

CONTRIBUTING.md
=> update  CONTRIBUTING.md

index.html
This Pull Request resolves issue #91
- Added Botpress chatbot that functions with AI and Webscraping data of the website itself.
=> Added Botpress bot with CDN

index.html
Removed social media handles from the header
- Closes #
[Issue number or description]
_Add your description_
- Closes #
[Issue number or description]
- [ yes] I have updated my branch and synced it with project `main` branch before making this PR
- [ yes] Is this a bug fix/enhancement/documentation changes
- [ yes] Part of GSSOC
- [ yes] Tested for any breaking changes
- [ yes] Other relevant checks completed
I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the …
=> Removed Social media handles in header solved issue#132

index.html
1. Implemented click-to-redirect functionality for contact information links, and
2. Resolved a bug where duplicate circles appeared in front of the phone number.
- Closes #181 
Fixed the issue where contact information links (location, email, and phone number) did not redirect to the default app on the user's device when clicked. Also removed duplicate circles in front of the phone number.
3. No portion of the work has been copied from any other source without proper attribution.  
4. The work has been checked for plagiarism, and I assure its authenticity.
I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any …
=> Enable Click-to-Redirect Functionality for Contact Information Links

index.html
_Add your description_ Correcting the spelling mistake
- Closes #
[Issue number or description]
- [ X] I have gone through the [contributing guide](## PR Description
_Add your description_
- Closes #
[Issue number or description]
- [ X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [ X] Is this a bug fix/enhancement/documentation changes
- [ X] I have updated my branch and …
=> Corrected the spelling mistake

README.md
Have added the necessary steps and images for the Project setup and how to run in local system of contributors to provide more clear instruction about the project
- Closes #162 
[Issue number or description]
[Issue no: #162] [[Docs]: Adding the Project setup and how to run locally ]
- [✅] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [✅] I have updated my branch and synced it with project `main` branch before making this PR
- [✅] Is this a bug fix/enhancement/documentation changes
3. The work has been checked for plagiarism, and I assure its …
=> Added project setup and how to run locally in documentation #162

index.html, style.css
Improvement in navigation bar.
if any problem kindly explain to me i will solve it. I have tried my best to improve this
Improve Navigation bar #138
- Closes #
Improve Navigation bar #138
_Add your description_
- Closes #
Improve Navigation bar #138
I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work.
=> Improve Navigation bar #138

index.html, style.css
=> Improved the UI by Color Changed and various location added

index.html, style.css
Added three input feilds time, hospital, opd section
- Fixes #150
=> Added section of input feild 

Css-Files/doctor.css, Html-Files/doc.html
From
To
Added a button to return to home page on the doctors page
also formatted the page to look cleaner
- Closes #
Fixes: #176 
- [v] I have gone through the [contributing guide](## PR Description
- [v] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [v] I have updated my branch and synced it with project `main` branch before making this PR
- [v] Is this a bug fix/enhancement/documentation changes
- [v] I have updated my branch and synced it with project `main` branch …
=> Fixes: No way to go navigate back #176

index.html, style.css
* ### Project name : #165 
* ### Short description : 
* changed the UI of the home page
=> changed the UI of the home page

index.html
_Add your description_ Adding copyright symbol
- Closes # 175
[Issue number or description] #175 
- [ ✅] I have gone through the [contributing guide](## PR Description
_Add your description_
- Closes #
[Issue number or description]
- [ ✅] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [✅ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ✅] Is this a bug fix/enhancement/documentation changes
- [✅ ] I have updated my branch and …
=> Added year near copyright symbol

.vscode/settings.json, Html-Files/Css-Files/styles.css, Html-Files/contact.html
=> add navbar in contact.html file

index.html
=> added logo and name on the home page

index.html, style.css
* ### Project name : #156 
* ### Short description : 
* changed the UI of the footer
=> Improved UI of footer

index.html
I have added Dynamic copyright details which fetches the current year and also i have made some changes like changed Designed by RapiDoc to made with love by RapiDoc.
- [✅ ] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [✅ ] I have updated my branch and synced it with project `main` branch before making this PR
- [✅ ] Is this a bug fix
- [✅ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ✅] Is this a bug …
=> Added Dynamic Copyright.

index.html, style.css
Improved the alignment of the Navbar items of the Rapi-Doc website along with the additional visual styling such as the Home page and about us page by using HTML, CSS, and Bootstrap.
- Closes #228 
Need to work a little more bit on Services and Make an appointment section which could be more enhanced by proper spacing and padding the items.
=> Changed alignments of the Home section and about us section with proper styling

.github/workflows/auto-comment-on-pr-merge.yml
I have added auto-comment-on-pr-merge.yml in .github/workflows directory. This file will add the feature of auto commenting when a pr is merged.
- Closes #276
=> Added the feature of auto commenting when a PR is merged

.github/workflows/codeql.yml
=> Add CODEQL analysis to the repo

index.html, style.css
Reverts Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-#326
the navbar orientation is messed up and the logo is too big also the feedback formed is not of appropriate bg color and sooo...
=> Revert "Added the Responsive ness and improved feedback,doctors,medical recor…"

README.md
I changes ReadMe.md file to automate the contributions of contributors.
as contributor contribute it automatically updates contributor list.
None
fixes #324
[x ] Feature enhancement
- [x ] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x ] I have updated my branch and synced it with project `main` branch before making this PR
- [x ] I have performed a self-review of my code
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.
=> Read me automation branch

.github/workflows/build-html-pages
I have added a workflow such that project builds for each commit in a PR.
Closes #355 
=> Add Support for Deployment 

style.css
=> Improved the layout of  Featured Services Section

index.html, style.css
Footer section designed using HTML and CSS with proper alignment , margin and padding along with the newsletter subscribe option.
- Closes #231
=> Proper alignment of the footer section task completed

index.html, style.css
=> Better documentation

.github/workflows/greetings.yml
I updated the post method in the code and I have also tested this on my local repository and it worked.
- Closes #363
- [] I have commented my code, particularly in hard-to-understand areas.
=> improve the PR comment workflow text: #363

index.html
The "Nearest Lab" logo was changed in the statistics section. 
None 
- Closes #234 
The Change was needed to get a better User experience
=> Logo updated

index.html
Twitter logo changed
Issue Number - #435 
- Closes #435 
=> twitter-logo-changed 

chatbox.css, chatboxx.js, index.html
=>  chatbox changes

Html-Files/cardio.html, Html-Files/derma.html, Html-Files/ent.html, Html-Files/gynaco.html, Html-Files/pediatrition.html, index.html, style.css
when appointing a doctor, all doctors from various categories are displayed in the horizontal scroll, including Dermatologists, Gynecologists, Cardiologists, and ENT specialists. To streamline user experience, I propose refining the horizontal scroll to only showcase doctors from the specific category being viewed
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/issues/26
- Closes https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/issues/26
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142529986/a7bbeaec-84c2-4773-9af7-7a …
=> Enhance Horizontal Scroll: Display Specific Category Doctors Only

Html-Files/error.css, Html-Files/error.js, Html-Files/error404.html, jsconfig.json
Error 404 page:
Hi, @Anishkagupta04 @varshith257 ,
I hope you're doing well. I've addressed the issue #442 and created a pull request to resolve it.
Could you please review the PR and let me know if any adjustments are needed?
Also, please assign the label according to my work, before merging.
Best regards,
Tanisha Garg
=> error 404 page

index.html
Closes #475 
Added functionality to feedback form
@varshith257 I have added javascript code for feedback form, now we can input details of feedback form, once clicked on submit button it displays a confirmation message and reset the forms for better practice.
please add gssoc and level label to it.
thank you
=> Added functionality to feedback form

index.html
Issue #476 
\Added functionality to contact form. The form now accept response, displays confirmation message and reset the forms after displaying the message which is a good practice.
@varshith257 ma'am please have a look. Also please add gssoc and level label. Please add my name in assignes as well.
thank you
=> Added functionality to contact form

index.html
solved issue #492 
I have changed the contact form style a bit and added the functionality, confirmation message as well. @Anishkagupta04 ma'am or @varshith257 sir please have a look. also please add gssoc and level label. Thank you
earlier
now
=> Enhance the contact page

index.html
I had improved the UI/UX of the website , I had fixed some parts of the website.
- Closes #418 
Please review my pull request.
=> Improved the UI/UX of the website

index.html, style.css
Aligned Service and Signin/Signup with the other elements of navbar
- Closes #506 506
GSSoC'24
=> Service and Signin/Signup changed

index.html
Removed the navbar that was below the main navbar
- Closes #508 
GSSoC'24
=> Removed another navbar

.vscode/settings.json, index.html, package-lock.json
Multilingual support has been added in website.
- Closes #514 
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/119414762/115c643b-7110-4d31-b9ea-9b220f8b6742
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/119414762/fb58525a-5778-4326-bf0c-f3cc7409f541
Kindly review the PR
=> Implementing Multilingual support #514

index.html, style.css
Hello Project Admin,
I Alligned Navbar Perfectly to make website  Look Attractive - Closes #540 
@varshith257 Please kindly go through it
=> Alligned Navbar

Html-Files/Doctor Experience.html, Html-Files/blood.html, Html-Files/list.html
issue #580
- Closes #580 
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/b5f6165a-49f7-4189-8a32-b1c1f0b4c496
=> ✨[Feature Request]: Enhancement of Blood Bank.html page

index.html, style.css
Customised the footer bottom and removed the small bottom to top arrow as there were two of them
- Closes #510 
=> redesigned footer

index.html
Hey @Anishkagupta04 , @varshith257 
issue closes #683 
- Added functionality to the "Testimonials" text in the footer to navigate to the testimonials section on the home page.
Privacy Policy Link:
- Correctly linked the "Privacy Policy" text in the footer to the privacy_policy_page.html file.
- Updated the footer HTML to include the correct links for the "Testimonials" and "Privacy Policy" texts.
- Ensured that both links are now functional and direct users to the appropriate sections/pages.
**Video Demonstration**
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/131389695/97467e25-215f-4b4c-b1eb-e15151732682
Please take a look. Looking forward to contribute more to the project :)
=> Added Functional Links to "Testimonials" and "Privacy Policy" 

Html-Files/news.html, index.html
In the website while hovering the text was not visible , i was resolve those bugs.
- Closes #610
Before:
After:
Before:
After:
Before:
After:
@Anishkagupta04, I have addressed the issue again due to conflicts. The previous PR #633 was closed, so please review my changes and merge them.
Thank you
=> Bug: Hovering errors were Resolved 

Html-Files/news.html
**In this I have changed the buttons in the news page with Cool Animated Buttons**
- Closes 
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/114290748/0410c287-963e-4e78-a726-d1c341731fc5
BEFORE:
AFTER:
@Anishkagupta04 please review this PR and give me feedback and please assign this PR to me under Gssoc24
=> News Page is been changed with Animated Buttons

index.html
All required changes are done in an avatar, input, and submit button
- Closes #605 
=> All changes done in avatar,input and submit button

Html-Files/contact.html, faq.html, index.html
I have changed the footer in faq page and The scrolling button is not working before I have fixed the scrolling button in faq page. I have added links in the footers of index page and faq page. The logo in Faq page is bug is fixed. 
- Closes #628 
- Closes #521 
before footer 
after footer in faq page 
Scroll button in faq page
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/97241435/9c70c019-62ae-46a2-b310-5a0e5af2c54d
There is no image showing in contact.html page I have fixed that too, now the image appears when the page is loaded.
=> changed the footer of faq page

rateus.css, rateus.html
I Have added the Footer section in RateUs page and also fixed the Navbar of it
- Closes #689 
=> Added footer and fixed the navbar of RateUs Page

index.html, news.html
Added icons to the navbar links and all the links successfully redirect to the required page
- Closes #585 
GSSoC'24
=> fixed the links in the nav bar

Html-Files/news.html, index.html
removed conflicts for feature-707
- Closes #707 
=> removed conflicts for feature-707

appointment.html
Added functionlaity to appointment form, now it is accepting the response correctly.
- Closes #755 
- [yes ] Bug fix
- [ yes] Documentation update
Uploading WhatsApp Video 2024-07-05 at 12.04.13_de1d0024.mp4…
- [y ] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [y ] I have updated my branch and synced it with project `main` branch before making this PR
- [y ] I have performed a self-review of my code
- [y ] I have tested the changes thoroughly before submitting this pull request.
- [y ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [y ] I have commented my code, particularly in hard-to-understand areas.
[Include any additional information or context that might be helpful for …
=> Update appointment.html added functionality to it

Html-Files/appointScript.js, Html-Files/appointment.html
Earlier the form was submiting the blank appointment form, i have made the desired changes  to avoid unnecessary blank form submission
- Closes #748 
- [yes ] Bug fix
- [ yes] Feature enhancement
- [ X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [ X] I have commented my code, particularly in hard-to-understand areas.
[Include any …
=> Improved functionlality of appointment form

Html-Files/appointment.html, Html-Files/customer_agreement.html, Html-Files/derma.html, Html-Files/news.html, Html-Files/privacy_policy_page.html, Html-Files/terms_and_conditions.html, test.html
Hey @Anishkagupta04 and @varshith257 ,
issue closes #751 
I have added the Scroll down progress bar in All pages of the website
******Screenshot******
******Type of PR******
Feature enhancement
Please take a look and review it
=> Added "Scroll Down Progress Bar" To The website 

index.html
Added confirmation message to newsletter form
Added a modal popup for subscription confirmation with a teal background and white text.
- Closes #803 
- [yes ] Feature enhancement
- [X ] I have commented my code, particularly in hard-to-understand areas.
=>  Add confirmation message to newsletter form

index.html
=> changed_twitter_icon

style.css
The text is changed to a color used in the navbar for the hover effect for Better Visibility.
Closes #802
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/146121869/424717af-c959-4ed6-87b9-79ec5b3b40e7
=> Fixed Footer Hover Text Color

Html-Files/news.html, index.html, style.css
add actual colour of social iicon on hover
- Closes #814 
https://github.com/user-attachments/assets/3a366e72-d713-4546-a4a6-40d95110a870
=> add hover in social icons 

index.html
i have linked the login page now the button should take us to the login page
- Closes #
=> link the login page

log/login.css, log/script.js
I have added login successful banner on top of the page when login is successful
- Closes #817
Before:
https://github.com/user-attachments/assets/157d3d22-8b34-455b-b2c4-cac4068056ee
After:
https://github.com/user-attachments/assets/65adfafd-772c-452c-969a-a748867063af
It is looking better and improved UI
=> add login successful popup

log/login.css, log/login.html
add hover on social icon of login
- Closes #866 
https://github.com/user-attachments/assets/c9f1bc64-199b-42eb-94ca-db6a4398bfb2
=> add hover on social icon of login

googletranslate.css, googletranslate.js, index.html
Added a google translate button which acts as a pop up and is aligned with the theme properly
- Closes #844 
https://github.com/user-attachments/assets/0ea3547e-8005-416c-ae12-a00393d2cb7f
GSSoC'24
=> added google translate button

faq.html
@varshith257  hi i have made the faq page responsive by adding a hamburgur icon for smaller screen so that the navbar is responsive 
made the footer resonsive and the elements in the page responsive removed unnecessary lines from the code 
#894 i have mentioned it in this issue  
- Closes #
Before : 
After:
=> made the faq page responsive 

log/login.css, log/login.html, log/script.js
When you click on eye it shows/hides password in login and register page
- Closes #816 
https://github.com/user-attachments/assets/9fa27501-0557-4111-9754-eb08a28beb3e
=> [FEAT] : Add password visibility in login/signup

index.html
=> fixed the footer login bug

index.css, index.html
This PR improves navbar for better visibility.
- Closes #925 
Before:
After:
=> Fixes issue #925

Html-Files/Doctor Experience.html, Html-Files/blood.html, Html-Files/bloodtest.html, Html-Files/news.html, Html-Files/privacy_policy_page.html, faq.html, index.html, medicine.html, news.html, test.html
changed text color of subscribe button
- [X ] Bug fix
- [ X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [ X] I have updated my branch and synced it with project `main` branch before making this PR
- [ X] I have performed a self-review of my code
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
=> Text color change

Html-Files/Doctor-Experience.html, index.css, index.html, news.html
Improved navbar alognments and styling in Find a doctor page and new page
- Closes #931
Before:
After:
Find a doctor-
News-
=> Fixes issue no. #931

index.html
Emoji Section added in Feedback Section
- Closes #804 
=> Emoji Section added in Feedback Section

Html-Files/Doctor Experience.html, Html-Files/Doctor-Experience.html, Html-Files/blood.html, Html-Files/bloodtest.html, Html-Files/news.html, faq.html, index.css, medicine.css, news.html, style.css, test.css, test.html
decrease size of  © 2024 RapiDoc | All Rights Reserved Made with ❤ by RapiDoc in every page of the repo.
#894 
Medicine.html
index.html
news.html
doctorexperince.html
test.html
bloodtest.html
blood.html
index.html
=> Fixes screen size of small html element in every html page.

dex.html
#940
- Closes #940 
Before changes
After changes
https://github.com/user-attachments/assets/b67f9acc-89e1-49e6-88e0-72f9ef4afde4
=> fixes header & footer of dex.html

index.html, style.css
When user enters details , in patient portal , login successful comes
- Closes #938 
https://github.com/user-attachments/assets/ea88478b-12ab-4eb1-bac2-712ceb7cb8ed
=> Added login successful popup in patient portal

index.html, style.css
-  add thanks for the feed back when submit feed back is pressed 
- Closes #942 
https://github.com/user-attachments/assets/4b34af15-f050-4869-9310-77e8dcdf5670
=> feat: add thanks for the feed back

index.html
#894 
Size decrement of Appointment section in index.html  and nav bar text size.
Size should be decreased such that to avoid gaps after the footer at right side as shown below
And text size in navbar must be decreased such that UI looks good.
- Closes #968 
https://github.com/user-attachments/assets/f7870981-1d2d-4cfd-88b9-d3aa2602eeb7
l information or context that might be helpful for reviewers.]
=> Size decrement of Appointment section in index.html  and nav bar text size

assets/css/visitors.css, assets/js/visitors.js, index.html
=> Visitors addition

Css-Files/testimonial.css, index.html
i have made the changes to the testimonial section you mentioned now you can use the arrow to go the next testimonial
- Closes #898
=> Update testimonial section

dex.html, index.css, index.html, js/tilt.js, medicine.css, medicine.html
#956
- Closes #956 
https://github.com/user-attachments/assets/a4c638d4-c5f4-44ad-b78e-1dc7d7469d26
=> tilt effect

index.html, style.css
This pull request aims to enhance the alignment and overall design of the footer on our website. The following changes have been implemented:
Adjusted the alignment of footer elements to ensure consistent spacing and layout.
Updated the color scheme to match the overall website design, including a pink shade for dark mode.
Added social media icons with links to the respective platforms.
Included a copyright section with the necessary details.
Refined the typography for better readability and aesthetics.
Please review this changes and approve
fixes issue #788
- Closes #
**Before**
**After**
Please review the changes and let me know if there are any further adjustments needed. I am open to feedback and suggestions to make sure the footer meets our design and functionality standards.
=>  Improve Alignment and Design of the Footer

Html-Files/privacy_policy_page.html
In the current privacy page the navbar is not fixed , and no action takes place on click of the hamburger icon of navbar .
I have fixed this issue and also replaced the logo with Rapidoc text in mobile view . Hence made this page responsive .
#894
- Closes #
https://github.com/user-attachments/assets/3a7f354c-f60f-42ce-b1da-18898c8844f8
=> Modified the Privacy Policy page and made it responsive .

news.html
I have added a progress bar on the news page similar to the home page .
- Closes #854
https://github.com/user-attachments/assets/bff73135-3e12-42f9-a401-ca0631643cb8
=> Added a progress bar on news page .

index.css, index.html
Enhanced the contact secction by making the the form and contact elements responsive.
- Closes #859 
BEFORE : 
AFTER : 
=> Enhanced the Contact Section

assets/css/styles.css
added hover effect to service page footer
Issue #833 
- [X ] Bug fix
- [ X] I have performed a self-review of my code
=> Footer hover

Css-Files/aboutus.css
Hello Project Admin
Fixed Mobile View of About Page as i have mentioned it in this issue #894 
Kindly Please go through this PR @varshith257 
https://github.com/user-attachments/assets/3afe7e4c-90f3-4003-ae46-d1b09c0ef4d2
=> Fixed Mobile View of About Page

Css-Files/input.css
Made input.html page responsive to small screen
issue #894 
- [X ] Feature enhancement
=> made-input.html-responsive

Css-Files/bloodstyle.css, Css-Files/doctor.css
- Closes 
Before
After 
1.Fix the Social icon height.
2.Dates boxes make visible in short screen sizes.
<!- [X] - put a cross/X inside [] to check the box -->
=> Gynacologist Section Responsiveness

Css-Files/aboutus.css, index.css, index.html
Improved the Patient Portal UI.
Aligned the cards properly in the Services section.
Ensured proper alignment of text fields in the Make an Appointment section.
Adjusted the cards in the About Us section.
- Closes #944 
Before:
https://drive.google.com/file/d/1NA8KsZMXZcUxLB84dmP90v3HBob_xIQi/view?usp=drive_link
After:
https://drive.google.com/file/d/1BGj8QYvTyFk9ZS2Ziq-RQ7uLo1p9Dyft/view?usp=drive_link
=> Fixes issue #944

index.html
Issue: #1019 
added correct file name to find-doctor button
=> added-correct-filename

assets/css/styles.css, dex.html
corrected link redirect for 'get started' button in dex.html
- Closes #1031 
- [ X] Bug fix
=> filename change

googletranslate.js, index.css, log/forgetpass.css, log/forgetpass.js, log/login.html, log/script.js, style.css
#984
Addition of forget password popup.
Forgetpassword has href="#"
**Before changes**
**After Changes**
https://github.com/user-attachments/assets/13520ee7-3ac5-4d03-8cad-693ce664c7dd
https://github.com/user-attachments/assets/99b0415b-fdf5-4970-b1b0-f1a2be396b20
https://github.com/user-attachments/assets/389499df-8f0e-4178-957a-bca58a5b8849
- Closes #984
=> Added Forget password popup

index.html
Sending confirmation email upon subscribing to the newsletter using EmailJS.
- Closes #1021 
[c62c59cb-84c1-4df9-b67e-7360b0c2d962.webm](https://github.com/user-attachments/assets/c6c1e257-0776-444c-ae25-b5922e486ac1)
=> Fixes issue #1021

index.css, index.html
Added a new styling of flipping the cards under the about us section and showing the new image when hovered. 
- Closes #1039 
https://github.com/user-attachments/assets/af35024d-7780-4a39-b53e-ab3f368be41b
=> Improved styling: flipping of cards nder about us

.github/workflows/auto-label-pr.yml
#991
- Closes #991 
"Settings" > "Actions" > "General" and under "Workflow permissions", select "Read and write permissions".
Make sure to do the above after PR merging.
=> Auto Label Added

Css-Files/Rateus.css, index.css, index.html, js/emailvalidation.js, style.css
#1044
- Closes #1044 
https://github.com/user-attachments/assets/404234fa-9f75-4e5d-97c3-886f00293628
=> Aligned and size decreased.

log/login.html
@Anishkagupta04 @varshith257 I have added LinkedIn Authentication to the website. Kindly review this.
- Closes #1047 
=> Adding LinkedIn Authentication

Html-Files/terms_and_conditions.html
Hey @varshith257 
issue closes #830 
I have created the terms and conditions page and make sure to add the navbar and footer in it 
I also made the page completely responsive
=> Created and Added  Terms and Condition Page

log/login.html
@Anishkagupta04 @varshith257 I have added Microsoft Authentication to the website. Kindly review this.
- Closes #1048 
=> Adding Microsoft Authentication

checkup.css, checkup.html, checkup.js, index.html
made the normaL checkup page mobile responsive
- Closes #1002 
https://github.com/user-attachments/assets/1a7dea12-8e1c-4ffa-afcc-b99a8c865f42
=> Made the normal check up page responsive

Html-Files/customer_agreement.html
i had mentioned it in
#894 
- Closes #
Before : 
After :
=> Fixed the customer agreement page (Added navbar and the full footer and made the page responsive)

log/login.html
@varshith257 @Anjaliavv51 I have added Github Authentication to the website. Kindly review this.
- Closes #1066
=> Adding Github Authentication

Css-Files/aboutus.css
Resolved issue #894 
About us section has been made responsive across all devices
@Anishkagupta04 can you please check and approve?
=> About us section - mobile responsive

index.css, index.html
added hover effect to 'appoint a doctor' button
Issue: #871 
- [X ] I have tested the changes thoroughly before submitting this pull request.
=> added-hover-to-btn

index.html
Issue : #1092 
redirect to login page on clicking register me
- [X ] I have tested the changes thoroughly before submitting this pull request.
=> linked-login.html

Css-Files/testimonial.css, index.html, js/testimonalslider.js
- Added prev and next button to the slides
- made slides per view to 1 and 2 for small devices
- add translate hover effects
- styled the rating 
- make the cards sizes similar
- added card change transition
- Closes #1100
https://www.awesomescreenshot.com/video/30090642?key=dd683fd85ecfca08ac1aef759b5cdf90
=> Enhanced the testimonials

Html-Files/Doctor Experience.html
direct to appointment.html on clicking on any doctor
issue: #1103
=> redirect to appointment page

Html-Files/Doctor Experience.html, Html-Files/blood.html, Html-Files/bloodtest.html, Html-Files/cardio.html, Html-Files/customer_agreement.html, Html-Files/ent.html, Html-Files/news.html, Html-Files/privacy_policy_page.html, Html-Files/terms_and_conditions.html, checkup.html, dex.html, index.html, medicine.html, news.html
added appointment link to navbar in all html files
issue: #1102
=> Updated Nav links

index.html, style.css
Hello Project Admin
I Enhaced Rate Us page and added hover effect and shining effect to Emojis - Solved #1036
Kindly go through this PR @varshith257 
https://github.com/user-attachments/assets/0cc7b2aa-81b3-464c-897c-106932d3be54
=> Enhanced Rate Us

index.html, style.css
Hello Project Admin
I Alligned Text on Home - Solved #1095 
Kindly go through this PR @varshith257
=> Alligned Text

Css-Files/testimonial.css
Fixed for mobile screen
- Closes #
=> Fixed the testimonial section for mobile screen

index.html
Fixed the register now button in Patient Portal.
- Closes #1143
=> Fixed register now button in Patient Portal

faq.html
Hey @varshith257 @Anishkagupta04 
issue closes #1138 
I have Completely improved the FAQ Page of the website - 
- **Added a "Search-Functionality"** to **filter out the questions** the customer needs faster
- The Search Functionality **Will display all the Questions** **matching the entered input** even if it is a single character
- **Added Interactive Hovering Effects** to the questions and Answers 
- **Added Main Heading and Introductory paragraph** to let users know a bit about the page 
- **Added Text Shadow to highlight the Important one's**
- Made the **Complete FAQ Page "Responsive" for all screen sizes** 
- Added Favicon to the page 
- I Have **Fixed the Inconsistent navbar issues**
- I **added correct navigating links to the links in the navbar** to redirect to respective page
- …
=> ✔️Improved the FAQ Page ( Fixed Navbar | Made Responsive )

.github/workflows/auto-label-pr.yml, Html-Files/appointment.html
#1107
Added favicon for twitter correctly , aligned nav bar in large screen , aligned navbar and footer in small screen too.
- Closes #1107
=> Updated the branch and added the code(bug)

news.html
Now logo is displayed on big screen and rapidoc text on smaller screen on the news page .
- Closes #1113
=> Now logo is displayed on big screen and rapidoc text on smaller screen on the news page .

Css-Files/aboutus.css
Added Card Style.
- Closes #1130
=> Added Hover on About Cards

index.html
in my earlier pull request i had made a separate page for patient portal but i forgot to remove it from the main page 
also i had linked it from the footer 
but forgot to link it from the navbar too 
I have fixed this 
Mentioned it in #1159 
- Closes #
=> removed the patient portal and linked it to the navbar

index.html
=> linked services

Html-Files/appointment.html, Html-Files/blood.html, Html-Files/bloodtest.html, about.html, aptmnt.html, checkup.html, checkup.js, dex.html, faq.html, helpline.html, index.html, js/about.js, js/faq.js, js/helpline.js
=> Feature : Added of reveal elements on scroll to remaining html pages

Html-Files/blood.html, Html-Files/cardio.html, Html-Files/customer_agreement.html, Html-Files/privacy_policy_page.html, Html-Files/terms_and_conditions.html, checkup.html, dex.html, medicine.html, news.html, test.html
=> Fixed the  footer for all the pages

log/login.html
I have added terms & conditions and privacy policy hyperlink to register and login page.
- Closes #1164
this closes issue opened by me #1164 
https://github.com/user-attachments/assets/dc034793-a0f9-42b0-b65f-40b4616c6130
please review and merge this pull request @varshith257 @Anishkagupta04
=> Added Terms and Conditions and Privacy Policy links

index.css, style.css
- Closes #1185 
size decreased
=> 🐞[Bug]: Decrease of font size in navbar and addition of effect the image
